version: "3"
services:
  golang:
    env_file:
    - .env
    image: golang:latest
    container_name: golang_con
    volumes:
      - ./golang.sh:/go/golang.sh
      - ./src/:/go/admin-api/
      - ./vendor/go/pkg:/go/pkg
      - ./vendor/go/src:/go/src
    command: bash -c "/go/golang.sh"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ENVIRONMENT: ${ENVIRONMENT}
      BASE_URL: ${BASE_URL}
    links:
      - database
    ports:
      - ${GOLANG_PORT}:${GOLANG_PORT}
  database:
    image: postgres:11.2-alpine
    container_name: database_con
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-dump:/home
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${PORT_DATABASE}:5432
    expose:
      - 5432
  adminer:
    image: adminer
    container_name: adminer_con
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - database
